format = "$all$time$line_break$jobs$battery$status$container$shell$character"

[directory]
truncation_length = 100
truncate_to_repo = false

[time]
disabled = false
time_format = "%F %T"
style = "yellow"
