format = "$all$time$cmd_duration$line_break$jobs$battery$status$container$shell$character"

[username]
show_always = true

[hostname]
ssh_only = false
style = "bold green"

[directory]
truncation_length = 100
truncate_to_repo = false

[git_status]
modified = "*"

[time]
disabled = false
time_format = "%F %T"
style = "yellow"

[cmd_duration]
style = "yellow"
